In [1]:
from sage.crypto.sbox import SBox
import numpy as np
import copy

In [2]:
S3 = SBox([1, 3, 6, 5, 2, 4, 7, 0])
S3_inv = S3.inverse()


S4 = SBox([0x2, 0xd, 0x3, 0x9, 0x7, 0xb, 0xa, 0x6, 0xe, 0x0, 0xf, 0x4, 0x8, 0x5, 0x1, 0xc])
S4_inv = S4.inverse()

## DDT

In [3]:
DDT3 = S3.difference_distribution_table()
DDT4 = S4.difference_distribution_table()

In [4]:
DDT3

[8 0 0 0 0 0 0 0]
[0 0 2 2 0 0 2 2]
[0 0 0 0 2 2 2 2]
[0 0 2 2 2 2 0 0]
[0 2 0 2 0 2 0 2]
[0 2 2 0 0 2 2 0]
[0 2 0 2 2 0 2 0]
[0 2 2 0 2 0 0 2]

In [5]:
DDT4

[16  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
[ 0  0  0  0  0  0  0  0  0  0  2  2  4  4  2  2]
[ 0  4  0  0  4  0  0  0  0  4  0  0  0  4  0  0]
[ 0  4  0  0  4  0  0  0  0  0  2  2  0  0  2  2]
[ 0  0  0  0  0  4  4  0  2  2  0  0  0  0  2  2]
[ 0  0  0  4  0  4  0  0  2  2  2  2  0  0  0  0]
[ 0  2  2  0  2  0  0  2  2  0  0  2  2  0  0  2]
[ 0  2  2  0  2  0  0  2  2  0  2  0  2  0  2  0]
[ 0  0  0  0  0  0  0  0  0  0  2  2  4  4  2  2]
[ 0  0  4  4  0  0  4  4  0  0  0  0  0  0  0  0]
[ 0  0  2  2  0  0  2  2  0  4  0  0  0  4  0  0]
[ 0  0  2  2  0  0  2  2  0  0  2  2  0  0  2  2]
[ 0  0  4  0  0  4  0  0  2  2  2  2  0  0  0  0]
[ 0  0  0  0  0  4  0  4  2  2  0  0  0  0  2  2]
[ 0  2  0  2  2  0  2  0  2  0  0  2  2  0  0  2]
[ 0  2  0  2  2  0  2  0  2  0  2  0  2  0  2  0]

## 1-1 DDT

In [150]:
DDT3_11 = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        DDT3_11[i][j] = DDT3[1<<i][1<<j]

DDT3_11

array([[0., 2., 0.],
       [0., 0., 2.],
       [2., 0., 0.]])

In [151]:
DDT4_11 = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        DDT4_11[i][j] = DDT4[1<<i][1<<j]

DDT4_11

array([[0., 0., 0., 0.],
       [4., 0., 4., 0.],
       [0., 0., 0., 2.],
       [0., 0., 0., 0.]])

## H-representation linear inequalities

In [6]:
FS = []

for i in range(2**len(S3)):
    for j in range(2**len(S3)):
        if(DDT3[i][j]):
            X = '0'*(4-len(bin(i)[2:])) + bin(i)[2:]
            Y = '0'*(4-len(bin(j)[2:])) + bin(j)[2:]
            LIS = []
            for elem in X+Y:
                LIS.append(eval(elem))
            FS.append(copy.deepcopy(LIS))      

            square_from_vertices = Polyhedron(vertices = FS)

list(square_from_vertices.inequality_generator())

[An inequality (0, 0, -1, 0, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, -1, 0, 0, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, 0, -1) x + 1 >= 0,
 An inequality (0, 0, 0, -1, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, 0, 0, -1, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, -1, 0) x + 1 >= 0,
 An inequality (0, 0, -1, 0, 0, 1, 1, 1) x + 0 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, 0, 1) x + 0 >= 0,
 An inequality (0, -1, 0, 1, 0, 1, 0, 1) x + 0 >= 0,
 An inequality (0, 0, 0, -1, 0, 1, 1, 1) x + 0 >= 0,
 An inequality (0, 0, 1, -1, 0, 0, 1, 1) x + 0 >= 0,
 An inequality (0, 0, 1, 0, 0, -1, 1, 1) x + 0 >= 0,
 An inequality (0, 1, 1, 1, 0, -1, 0, 0) x + 0 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, 1, 0) x + 0 >= 0,
 An inequality (0, -1, 1, 0, 0, 0, 1, 1) x + 0 >= 0,
 An inequality (0, 0, -1, 1, 0, 1, 0, 1) x + 0 >= 0,
 An inequality (0, 1, 1, 1, 0, 0, 0, -1) x + 0 >= 0,
 An inequality (0, -1, 1, 1, 0, 0, 0, 1) x + 0 >= 0,
 An inequality (0, 0, 0, 0, 0, 1, 0, 0) x + 0 >=

In [7]:
square_from_vertices = Polyhedron(vertices = FS)

len(list(square_from_vertices.inequality_generator()))

42

In [8]:
FS = []

for i in range(2**len(S4)):
    for j in range(2**len(S4)):
        if(DDT4[i][j]):
            X = '0'*(4-len(bin(i)[2:])) + bin(i)[2:]
            Y = '0'*(4-len(bin(j)[2:])) + bin(j)[2:]
            LIS = []
            for elem in X+Y:
                LIS.append(eval(elem))
            FS.append(copy.deepcopy(LIS))      

            square_from_vertices = Polyhedron(vertices = FS)

list(square_from_vertices.inequality_generator())

[An inequality (0, -1, 0, 0, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (-1, 0, 0, 0, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, 0, -1, 0, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, -1, 0, 0, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, 0, 1) x + 0 >= 0,
 An inequality (0, -1, -1, -1, -1, 0, 0, -1) x + 4 >= 0,
 An inequality (0, 0, 0, 0, -1, 0, 0, 0) x + 1 >= 0,
 An inequality (-1, -1, -1, -1, 0, -1, 0, -1) x + 5 >= 0,
 An inequality (0, 0, 0, 0, 0, -1, 0, 0) x + 1 >= 0,
 An inequality (0, 0, 0, 0, 0, 0, -1, 0) x + 1 >= 0,
 An inequality (0, 0, -1, 1, -1, 0, -1, 1) x + 2 >= 0,
 An inequality (0, -1, -1, 0, -1, 0, 1, -1) x + 3 >= 0,
 An inequality (0, 0, -1, -1, -1, 0, 1, -1) x + 3 >= 0,
 An inequality (-1, 1, 0, -1, 0, 0, 1, 0) x + 1 >= 0,
 An inequality (0, 1, -1, 0, -1, 0, 1, 1) x + 1 >= 0,
 An inequality (-1, 0, 1, -1, 0, -1, 1, 1) x + 2 >= 0,
 An inequality (-1, 1, -1, 0, 0, 0, 1, 1) x + 1 >= 0,
 An inequality (0, 0, -1, -1, 0, -1, 1, -1) x + 3 >= 0,
 An inequality (0, -1,

In [9]:
square_from_vertices = Polyhedron(vertices = FS)

len(list(square_from_vertices.inequality_generator()))

230

## Boomerang Connectivity Table

In [12]:
S3.boomerang_connectivity_table()

[8 8 8 8 8 8 8 8]
[8 0 2 2 0 0 2 2]
[8 0 0 0 2 2 2 2]
[8 0 2 2 2 2 0 0]
[8 2 0 2 0 2 0 2]
[8 2 2 0 0 2 2 0]
[8 2 0 2 2 0 2 0]
[8 2 2 0 2 0 0 2]

In [13]:
S4.boomerang_connectivity_table()

[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16]
[16  4  0  0  4  0  0  0  0  4  2  2  4  8  2  2]
[16  8  0  0  8  0  0  0  0  8  0  0  8 16  0  0]
[16  4  0  0  4  0  0  0  0  4  2  2  4  8  2  2]
[16  0  4  4  0  8  4  4  2  2  0  0  0  0  2  2]
[16  0  4  4  0  8  4  4  2  2  2  2  0  0  0  0]
[16  2  2  0  2  0  0  2  2  0  0  2  2  0  0  2]
[16  2  2  0  2  0  0  2  2  0  2  0  2  0  2  0]
[16  4  0  0  4  0  0  0  0  4  2  2  4  8  2  2]
[16  0  8  8  0 16  8  8  0  0  0  0  0  0  0  0]
[16  4  2  2  4  0  2  2  0  4  0  0  4  8  0  0]
[16  0  2  2  0  0  2  2  0  0  2  2  0  0  2  2]
[16  0  4  4  0  8  4  4  2  2  2  2  0  0  0  0]
[16  0  4  4  0  8  4  4  2  2  0  0  0  0  2  2]
[16  2  0  2  2  0  2  0  2  0  0  2  2  0  0  2]
[16  2  0  2  2  0  2  0  2  0  2  0  2  0  2  0]

## Boomerang Difference Table

In [10]:
import numpy as np

BDT3 = np.zeros((2**len(S3),2**len(S3),2**len(S3)))

for i in range(2**len(S3)):
    for j in range(2**len(S3)):
        for k in range(2**len(S3)):
            for x in range(2**len(S3)):
                if(S3[x]^^S3[x^^i]==j):
                    if(S3_inv[S3[x]^^k]^^S3_inv[S3[x^^i]^^k]==i):
                        BDT3[i][j][k]+=1

BDT3

array([[[8., 8., 8., 8., 8., 8., 8., 8.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [2., 0., 2., 0., 0., 0., 0., 0.],
        [2., 0., 0., 2., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 0., 0., 2., 0.],
        [2., 0., 0., 0., 0., 0., 0., 2.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [2., 0., 0., 0., 2., 0., 0., 0.],
        [2., 0., 0., 0., 0., 2., 0., 0.],
        [2., 0., 0., 0., 0., 0., 2., 0.],
        [2., 0., 0., 0., 0., 0

In [11]:
import numpy as np

BDT4 = np.zeros((2**len(S4),2**len(S4),2**len(S4)))

for i in range(2**len(S4)):
    for j in range(2**len(S4)):
        for k in range(2**len(S4)):
            for x in range(2**len(S4)):
                if(S4[x]^^S4[x^^i]==j):
                    if(S4_inv[S4[x]^^k]^^S4_inv[S4[x^^i]^^k]==i):
                        BDT4[i][j][k]+=1
                        
BDT4

array([[[16., 16., 16., ..., 16., 16., 16.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 4.,  0.,  0., ...,  4.,  0.,  0.],
        [ 2.,  0.,  0., ...,  0.,  2.,  0.],
        [ 2.,  0.,  0., ...,  0.,  0.,  2.]],

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 4.,  4.,  0., ...,  4.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 4.,  4.,  0., ...,  4.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

       ...,

       [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.